// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string | number;
  createdAt?: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: 'ADMIN' | 'USER';
  teamId: string;
  bio: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

export type Recipe = Entity<{
  id: string;
  title: string;
  image: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  rating: number;
  category: string;
  favorite: boolean;
}>;

export type Task = Entity<{
  id: number;
  title: string;
  category: string;
  assignedTo: number;
  dueDate: string;
  completed: boolean;
}>;

export type Event = {
  id: number;
  title: string;
  date: string;
  time: string;
  category: string;
  participants: number[];
  description: string;
};

export type FamilyMember = {
  id: number;
  name: string;
  initials: string;
  image: string;
};

export type Ingredient = {
  id: string;
  name: string;
  quantity: number;
  unit: string;
  note?: string;
};
